data:
  path: "./data"
  column: "Scalar B, nT"
  year: 2015               # Конкретный год (или "all" для всех)
  missing_values:
    - 9999.99
    - 99999.9

distribution:
  type: "burr"           # demo (N(0,1)) / normal / burr / gamma

plot:
  title: "QQ-plot для модуля ММП"
  show_line: true          # Показывать линию y=x
  limits: [0, 20]     # Границы значений осей
  save_format: "png"       # png / pdf / svg
  output_dir: "./results"    # Куда сохранять графики